"""empty message

Revision ID: a0f0f18e84a4
Revises: ffdc0a98111c
Create Date: 2023-03-22 12:08:29.474752

"""
from alembic import op
import sqlalchemy as sa


import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'a0f0f18e84a4'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Blocks', 'block_order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Blocks', sa.Column('block_order', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
